# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Internal Build"
  lane :beta do
    gradle(task: "clean bundleRelease")
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
    versions = google_play_track_version_codes(track: "internal")
    version_code = versions[0]
    upload_to_play_store(track: 'internal', version_code: version_code + 1, aab: "../build/app/outputs/bundle/release/app-release.aab", release_status: "draft")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
