# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build and Deploy to Google Play Internal App Sharing"
  lane :beta  do
    Dir.chdir "../.." do sh("flutter", "build", "appbundle", "--release") end # Call Flutter Build
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )

    previous_build_number = google_play_track_version_codes(track: "internal")[0]

    current_build_number = previous_build_number + 1

    version_name = flutter_version()["version_name"]

    sh "git config --global user.email 'lequyha98@gmail.com'"
    sh "git config --global user.name 'lequyha'"

    add_git_tag(
      prefix: "v#{version_name}-",
      build_number: current_build_number,
    )

    upload_to_play_store(
      track: 'internal', 
      version_name: "Version " + version_name,
      version_code: current_build_number, 
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      release_status: "draft",
    )

    push_to_git_remote 
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
