# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/upload-keystore.jks'
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Install dependencies
        run: flutter pub get

      - name: Run project source
        run: flutter run
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_KEYALIAS_PASS }}
          SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASS }}
