# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  JAVA_VERSION: "12.x"
  FLUTTER_CHANNEL: "stable"
  PROPERTIES_PATH: "./android/key.properties"
  STORE_FILE_PATH: "./android/upload-keystore.jks"


jobs:
  flutter_test:
    name: Run Flutter assigned build appbundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{env.FLUTTER_CHANNEL}}

      - name: Creating the key.properties file
      - run: |
          echo keyPassword=\${{ secrets.ANDROID_KEYALIAS_NAME }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.ANDROID_KEYSTORE_PASS }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.ANDROID_KEYALIAS_NAME }} >> ${{env.PROPERTIES_PATH}}

      - name: Decoding base64 key into a file
      - run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > ${{env.STORE_FILE_PATH}}
          echo storeFile=\${{ env.STORE_FILE_PATH }} >> ${{env.PROPERTIES_PATH}}

      - run: flutter pub get

      - run: flutter build appbundle


